spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/hebada?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: hyxSKY19920615
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      max-file-size: 2MB
    encoding:
      charset: utf-8
      force: true
      enabled: true
