spring:
  datasource:
    url: jdbc:mysql://localhost/hebada?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234
    driver-class-title: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      max-file-size: 2MB
server:
  port: 80

